/**
 * Writes docs/IMAGE_GUIDE.md from the image manifest.
 *
 *   pnpm images:guide
 *
 * The manifest is the single source of truth for what each picture is, where it appears and
 * what should replace it. Generating the guide means the document can never drift from the
 * code, which is what would otherwise happen the first time someone adds an image in a hurry.
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { photos, placeholders, type ImageEntry } from '../src/seed/image-manifest.js'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT = path.join(ROOT, 'docs', 'IMAGE_GUIDE.md')

/** Escapes the pipe characters that would otherwise break a Markdown table row. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|')
}

function placeholderSection(entry: ImageEntry): string {
  return [
    `### ${entry.slot}`,
    '',
    `- **Replaces:** \`${entry.slug}.webp\``,
    `- **Shape:** ${entry.aspect}`,
    `- **Photograph to take:** ${entry.brief ?? '[brief missing from the manifest]'}`,
    `- **Alt text once replaced:** ${entry.alt.replace(/^Placeholder image standing in for /, '')}`,
    '',
  ].join('\n')
}

async function main() {
  const lines: string[] = []

  lines.push(
    '# Image guide',
    '',
    '<!-- Generated by `pnpm images:guide`. Edit src/seed/image-manifest.ts, not this file. -->',
    '',
    'Every picture on the site, what it is, and where it appears.',
    '',
    '## House rules',
    '',
    '- **Alt text** follows `[Who] [doing what] [where] at Alliance High School Nansana`. An',
    '  upload without alt text is rejected.',
    '- **Uniforms** must match the real ones: a white shirt with a red or striped tie and grey',
    '  trousers or skirt, or a cream shirt with a brown skirt or trousers.',
    '- **Consent**: a photograph in which a student is recognisable needs the parent\'s consent',
    '  before it is published. Never photograph students in a dormitory.',
    '- **Originals** go in `assets/` at full resolution (git-ignored). `pnpm images` produces',
    '  the optimised copies the site actually uses: EXIF orientation applied, all metadata',
    '  including GPS stripped, long edge capped at 2400 px, WebP, plus a blur placeholder.',
    '- **Video** is embedded from YouTube behind a click-to-load facade. Never autoplay with sound.',
    '',
    `## Real photographs in use (${photos.length})`,
    '',
    'These are the school\'s own photographs. Nothing to do.',
    '',
    '| Where it appears | Shape | Alt text |',
    '|---|---|---|',
  )

  for (const entry of photos) {
    lines.push(`| ${cell(entry.slot)} | ${entry.aspect} | ${cell(entry.alt)} |`)
  }

  lines.push(
    '',
    `## Placeholders to replace (${placeholders.length})`,
    '',
    'These are AI-generated stand-ins. They are labelled "Placeholder image" wherever they',
    'appear, because an invented picture must never be passed off as a photograph of a real',
    'event at the school. Each one below says exactly what to photograph to replace it.',
    '',
    '**To replace one:** put the photograph in `assets/`, point its manifest entry at the file,',
    'change `kind` to `photo`, remove `brief`, then run `pnpm images && pnpm seed`.',
    '',
  )

  for (const entry of placeholders) {
    lines.push(placeholderSection(entry))
  }

  lines.push(
    '## A note for whoever does the photography',
    '',
    'One morning with a camera would replace most of this list. Shoot in the morning when the',
    'light is soft, keep the horizon straight, and leave empty space on one side of the wide',
    'shots so a headline can sit there without covering anyone\'s face. Wide shots of the campus',
    'and a clear, straight-on photograph of the main gate signboard matter most: the gate shot',
    'is what Google shows beside the school in search results.',
    '',
  )

  await fs.mkdir(path.dirname(OUT), { recursive: true })
  await fs.writeFile(OUT, `${lines.join('\n')}`, 'utf8')

  console.log(`docs/IMAGE_GUIDE.md written: ${photos.length} photographs, ${placeholders.length} placeholders`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
